### ISSUE TITLE
Injecting parameters to dagster ops/job

### ISSUE THREAD

**Issue by slamer59** [quantile-development/dagster-meltano#19]
Hello,
I have a run like this: 
`meltano run tap-rest-api-msdk target-jsonl`

and a **meltano.yaml**
```
plugins:
  extractors:
  - name: tap-rest-api-msdk
    variant: widen
    pip_url: tap-rest-api-msdk
    config:
      api_url: ...
      streams:
       - name: ...
         ...
         params:
           date_after: 01/01/2021
           ...
         primary_keys:
         - id
```

Is it possible to override parameters and inject them with `_defs` definitions at any level ? 

Reading your code it is not feasible (due to command.split()). And meltano does not allow to inject variable via CLI. Only override meltano.yaml or with environment variable injection which we cannot do since dagster is running. 

How would you override on the fly the **date_after** withtout touching the file ?
