### ISSUE TITLE
set dagster version?

### ISSUE THREAD

**Issue by ReneTC** [quantile-development/dagster-meltano#42]
Does anyone know where the dagster version is set? I am not sure, but it seems dagster is installed via this package.
The versions are:
```
dagster: 1.3.2
daagster-dbt: 0.19.2
```

can we upgrade, or am i in the wrong place?
edit//
Or maybe it is here instead? https://github.com/quantile-development/dagster-ext

**Comment by JulesHuisman** [comment]
The version is set here: https://github.com/quantile-development/dagster-meltano/blob/f4410d24587540400b7cffcd012a4711e91c0a42/pyproject.toml#L14

But you can simply install a specific Dagster version in the same environment. 

E.g. `pip install dagster-meltano dagster==1.5.0`

**Comment by ReneTC** [comment]
Thanks for the suggestion.
I need to upgrade to get some new features out of Dagster. For the Meltano dagster -utilty it also install dagster-ext? I don't recall installing that manually so my meltano.yml looks like this:
```
  - name: dagster
    variant: quantile-development
    pip_url: dagster-ex 
    config:
      repository_dir: ${MELTANO_PROJECT_ROOT}/orchestrate
```
This gives me the versions I posted before. Trying to upgrade with your suggestion is:
```
  - name: dagster
    variant: quantile-development
    pip_url: dagster-ex dagster==1.5.0
    config:
      repository_dir: ${MELTANO_PROJECT_ROOT}/orchestrate
```
But during install, this result in conflicts:
`Utility 'dagster' could not be installed: failed to install plugin 'dagster'.
ERROR: Cannot install dagster-ext, dagster-ext==0.1.0 and dagster==1.5.0 because these package versions have conflicting dependencies.`
