### ISSUE TITLE
Test tap and target config capabilities

### ISSUE THREAD

**Issue by JulesHuisman** [quantile-development/dagster-meltano#6]
Make sure the tap and target configurations injection works with more complex values like:
```yaml
config:
      files:
        - entity: "sample"
          path: extract/sample.csv
          keys: ["id"]
```
It currently injects the configuration using environment variables. 

```python
@property
def _target_config_env_vars(self):
    return {
        lower_kebab_to_upper_snake_case(f"{self._target}_{config_name}"): value
        for config_name, value in self._target_config.items()
    }
```
